### ISSUE TITLE
unhelpful ./configure message

### ISSUE THREAD

**Issue by ojcharles** [Adrian-Cantu/pprinseqc#16]
What I was doing: Install via git clone as in readme

Command run "./configure"

Error message
"
./configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features by default... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for boostlib >= 1.41 (104100)... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
"

Issue: The last line of that output is not terribly helpful for me to try and rectify the install.

Any chance this can be rectified, I like the idea of Prinseq++ 👍 

Thanks

edit : After further reading of the configure file, I sussed I needed the c++ boost library, when installed everything worked like a charm. But weird that was not mentioned in the above. Hopefully thats helpful :)

**Comment by ojcharles** [comment]
You closed this, but the error message is still unhelpful.
Others should not need to hunt for the correct library, you should make the message explicit, please  re-open.

**Comment by Adrian-Cantu** [comment]
I changed the error message for all boost libraries 
https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/blob/0968234d07e97b621089c1983b5b0dd7c36eb99e/m4/ax_boost_filesystem.m4#L107
https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/blob/0968234d07e97b621089c1983b5b0dd7c36eb99e/m4/ax_boost_iostreams.m4#L106
https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/blob/0968234d07e97b621089c1983b5b0dd7c36eb99e/m4/ax_boost_system.m4#L111
Thanks a lot for the feedback

**Comment by ojcharles** [comment]
Cracking thanks :)
