### ISSUE TITLE
Bug: `-noiupac` options filters out all reads

### ISSUE THREAD

**Issue by fgvieira** [Adrian-Cantu/pprinseqc#5]
I've been trying different sets of filters and all seems to work fine, except for the `-noiupac` filter that filters out all reads even though they only have IUPAC letters.

Could this be a bug?
thanks,

**Comment by Adrian-Cantu** [comment]
were you using RNA? it was a bug, "U" was considered a iupac extended base. it is now fixed in the 1.2 version

**Comment by fgvieira** [comment]
Seems to be working now.
thanks,
