### ISSUE TITLE
Please add support for -phred64 option

### ISSUE THREAD

**Issue by brbatv** [Adrian-Cantu/pprinseqc#6]
Hello, thank you very much for your implementation, it is indeed much quicker than the original !!

One thing that is missing is the original -phred64 option, because by default prinseq only recognises quality from sanger, and If I have data from illumina 1.5 for example, I'd need to convert all my fq files, which is quite long.

Thank you for your attention

**Comment by brbatv** [comment]
Actually, converting filles from illumina 1.5 to sanger is not that long using biopython, 1 or 2 minutes for a 5Gb file, but adding native support could be nice ;)

**Comment by Adrian-Cantu** [comment]
Version 1.2 is out and it has that functionality =)
