### ISSUE TITLE
Please add the -trim_left and -trim_right option from the old prinseq

### ISSUE THREAD

**Issue by pjtorres** [Adrian-Cantu/pprinseqc#7]
Great program @Adrian-Cantu. Really fast compared to the old prinseq.  Could you please add the trim function from prinseq into prinseq++? An example of the command in prinseq  was  ```-trim_left 4 -trim_right 15```. This way I can trim my sequences even if there are no poly aa tails or if the sequence is high quality. Thanks!

**Comment by Adrian-Cantu** [comment]
Version 1.2 is out and it has that functionality =)
